### ISSUE TITLE
Cannot skip existing files

### ISSUE THREAD

**Issue by 1223334444abc** [elvis972602/Kemono-scraper#10]
Something's wrong, this problem has reappeared. This time, I did not open any other software.

The software will continuously try to write to the existing image number 0, and it will be rejected. Repeat many times until successful after about ten minutes.

**I found that the program was constantly creating. tmp files, and when I tried to delete the existing 0.jpg, it would prompt that the file was occupied by "kemono scraper. exe".**

![图片](https://github.com/elvis972602/Kemono-scraper/assets/111836697/3037caf4-1fcc-4239-b64d-b95c382ac4ec)
![图片](https://github.com/elvis972602/Kemono-scraper/assets/111836697/7245b356-9de8-4730-bd4c-123eac9b1042)

![图片](https://github.com/elvis972602/Kemono-scraper/assets/111836697/f7d2b92e-6af1-44fb-9e3c-d77d724883a9)

**Comment by elvis972602** [comment]
I see. Maybe it didn't close the file and then re-download the file. I'll try to fix it.

**Comment by 1223334444abc** [comment]
It should be like this. When I manually pause the program for about ten seconds before continuing, this issue will be resolved.

> I see. Maybe it didn't close the file and then re-download the file. I'll try to fix it.
