### ISSUE TITLE
How do I build this from source

### ISSUE THREAD

**Issue by SupahFox** [elvis972602/Kemono-scraper#18]
Tried doing  `go mod download` and `go build` on /main

Idk if i'm doing this correctly as I don't have knowledge using go lang

**Comment by elvis972602** [comment]
I add it in [build-from-source](https://github.com/elvis972602/Kemono-scraper#build-from-source)

**Comment by SupahFox** [comment]
> I add it in [build-from-source](https://github.com/elvis972602/Kemono-scraper#build-from-source)

Thanks!

**Comment by SupahFox** [comment]
It seems that when I try to build it, returns `no Go files in \Kemono-scraper` (root of the repository)

**Comment by elvis972602** [comment]
After you build it, there should be an exe file that appears in `Kemono-scraper\main`

**Comment by elvis972602** [comment]
I'm sorry, I misread your question. You should go to the `main` folder.

**Comment by SupahFox** [comment]
> I'm sorry, I misread your question. You should go to the `main` folder.
> 
> ```shell
> cd Kemono-scraper/main
> ```

Thanks 👍
