### ISSUE TITLE
How to update the database

### ISSUE THREAD

**Issue by 1223334444abc** [elvis972602/Kemono-scraper#19]
I tried:

date-after: 20230531
update-after: 20230531

Whether they are written in the configuration file simultaneously or separately, new posts from June and July cannot be downloaded.

I hope to have incremental updates to the database: download new posts and update posts with changes. How should I write the configuration file?

Are there any conflicting relationships between different settings? A clearer explanation is indeed needed. 
Does "-- date" represent the upload date of the post on the source website, and "-- update" represent the modification date of the post on Kemono? Can these two settings be used simultaneously and what specific effects will they have?

**Comment by elvis972602** [comment]
I apologize, I seem to have set the wrong variable name...
And I will add a detailed tutorial document soon.

**Comment by 1223334444abc** [comment]
Once there is any fluctuation in the network that leads to a loss of connection, the program will only retry three times and then exit. (Actually, the network connection will be restored in a very short time)

**Comment by elvis972602** [comment]
I would change it to have the same number of retries and wait intervals as the downloaded file.

**Comment by 1223334444abc** [comment]
.exe need

**Comment by elvis972602** [comment]
[release](https://github.com/elvis972602/Kemono-scraper/releases)

**Comment by 1223334444abc** [comment]
After I specified 'date after: 20230531 update after: 20230531', all posts of this creator (https://kemono.party/patreon/user/82814471) will be mistakenly skipped.

Because this is the creator of my new focus, I noticed this problem. There may be other posts mistakenly skipped.

![image](https://github.com/elvis972602/Kemono-scraper/assets/111836697/e84f693c-c48a-4cad-abdb-2f4a8d946cb9)
(Complaint about the usage instructions.)

**Comment by elvis972602** [comment]
date : publish time
update : edit, update time
`date after: 20230531 update after: 20230531` means publish after 20230531 __AND__ edit after 20230531
It will be skepped because the edit date is empty, which means it has not been edited.

**Comment by 1223334444abc** [comment]
Will I successfully update my database by running these two options separately? 

If the logic of "or" can be added, it will greatly improve efficiency.
