### ISSUE TITLE
Bug: The rar file is wrongly downloaded as a file in .bin format

### ISSUE THREAD

**Issue by MVPAIR** [elvis972602/Kemono-scraper#22]
The same thing also happens when download .ini file, and .zipmod file is downloaded as a .zi.zip file

**Comment by elvis972602** [comment]
Could you provide the download URL and configuration?

**Comment by MVPAIR** [comment]
.zipmod : https://kemono.party/patreon/user/82206231/post/83551779
.ini : https://kemono.party/patreon/user/88511381/post/83610295
.rar : https://kemono.party/patreon/user/79167578/post/86162232
you can use these link to test, but i think this scraper just convert all unrecognized file formats to .bin files, so there must be problems with files other than these formats

**Comment by MVPAIR** [comment]
https://github.com/Kochisa/kemono-dl
This guy has solved this problem in python, but I like your software better, because your software has a better naming and indexing function for different formats of files when downloading them.

**Comment by elvis972602** [comment]
This seems to be caused by different URLs and file name extensions.
For example in url is `xxxx.zip` but filename is `xxxx.zipmod`, however i can't download the rar file from the link you provided, the URL leads to a website not a file.
