### ISSUE TITLE
Error encountered in a post with no content

### ISSUE THREAD

**Issue by 1223334444abc** [elvis972602/Kemono-scraper#27]
https://kemono.party/fanbox/user/38270352/post/5039511

The program reports an error and exits directly: "panic: runtime error: index out of range [-1]"
The official said that this type of post is caused by a blacklist, and I think it can be directly ignored. 
(Does anyone know what a blacklist means?)

https://kemono.party/fantia/user/1888/post/492773
And in this post, the downloader download three extra txt files.

"An existing connection was forcibly closed by the remote host."
I have often encountered such mistakes recently, and they will be resolved in a few minutes. It seems that the website is restricting downloads?

**Comment by elvis972602** [comment]
I'm sorry I completely forgot about this issue, regarding the second question, the api has a `name` field, which in some images named txt is indeed txt. 
I think this is a special case and unpredictable. I also use other downloaders such as [gallery-dl](https://github.com/mikf/gallery-dl) and have the same problem, so this should not be fixed.
