### ISSUE TITLE
Any way to download text from posts?

### ISSUE THREAD

**Issue by SupahFox** [elvis972602/Kemono-scraper#28]
Just asking this because I don't see any reference on [README.MD](https://github.com/elvis972602/Kemono-scraper/blob/master/README.md)

**Comment by elvis972602** [comment]
Can use `content <bool>` to download text as html

**Comment by SupahFox** [comment]
Reopened this as it didn't work with any kemono page

**Comment by SupahFox** [comment]
It didn't work with any kemono page

**Comment by elvis972602** [comment]
Can you provide the URL  and the config?

**Comment by SupahFox** [comment]
```/main.exe --link "https://kemono.party/patreon/user/60512109" --template "<ks:service>/<ks:creator>/<ks:post>/<ks:filename><ks:extension>" --banner true --content true```

**Comment by SupahFox** [comment]
@elvis972602 any clue?

**Comment by elvis972602** [comment]
I'm very sorry for replying so late. You should use `--banner` or `--banner=true` for the bool flag, and cannot use `--banner true`
