### ISSUE TITLE
"Cookie is empty"

### ISSUE THREAD

**Issue by SH0D4N-1337** [elvis972602/Kemono-scraper#30]
Hi,
I can't seem to make cookies.txt work.

File `cookies.txt` contains:
```
kemono.party	FALSE	/	FALSE	1697535614	session	[token]
coomer.party	FALSE	/	FALSE	1697289572	session	[token]
```
I tried adding dot on beginning, change 2nd FALSE to TRUE, change session to kemono_auth or commer_auth, because your example is different from what cookie export gives you.
<details>
  <summary>Your example</summary>
  <kbd>
### Cookie File
only needed if you want to download favorite creators or posts  
  
`--cookie PATH`  
cookie file, default is cookies.txt (value separate by whitespace)  
syntax:  

| Domain        | Include subdomains | Path | Secure | Expiry     | Name        | Value   |
|---------------|--------------------|------|--------|------------|-------------|---------|
| .kemono.party | FALSE              | /    | TRUE   | 1706755572 | kemono_auth | <value> |

you can get cookies easily by using Chrome extension [Get cookies.txt LOCALLY](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc)</kbd>
</details>

I get this error:
`2023/09/17 12:37:06 cookie is empty`

Regardless if I do:
`.\kemono-scraper_no_cookies_detection.exe`
`.\kemono-scraper_no_cookies_detection.exe --cookie .\cookies.txt`
I tried full path to the `cookies.txt` file, backslash and quotes.

Config:
```
cookie: .\cookies.txt
content: true
banner: true
async: true
max-download-parallel: 5
fav-site: coomer
fav-creator: true
output: D:\kemono-scraper
template: "[<ks:service>] <ks:creator>/<ks:post>/<ks:filename><ks:extension>"
image-template: "[<ks:service>] <ks:creator>/<ks:post>/<ks:index><ks:extension>"
video-template: "[<ks:service>] <ks:creator>/<ks:post>/video/<ks:filename><ks:extension>"
retry: 10
retry-interval: 15
# proxy: socks5://proxy:1080
```
I once again tried full path to the `cookies.txt` file, backslash and quotes.

I have to use the version with detection and even that  has to be pointed on a browser that is not being used, otherwise I'll get an error like this:
```
2023/09/17 13:56:15 Error reading cookies: could not open database copy: could not read database file: 
open C:\Users\shodan\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies: 
The process cannot access the file because it is being used by another process.
```
Am I doing something wrong? Can you add an option to use the cookie token in CLI for example?

Is it possible to run more processes at once? Because I thought the `max-download-parallel` refers to how many posts or creators are being scraped at once, but it seems to work only if currently scraped post has more of files inside of it.

**Comment by elvis972602** [comment]
I found an error where I was looking for the file, and I'll fix it as soon as I can.
Regarding not being able to access the cookie database with the browser open, it seems that this has been the case since the previous chrome update.

**Comment by SH0D4N-1337** [comment]
> Regarding not being able to access the cookie database with the browser open, it seems that this has been the case since the previous chrome update.

I reckon that even when I tried Firefox while I had it open it had the same error. But Firefox runs on Chromium, so it could copy the same issue.

**Comment by SH0D4N-1337** [comment]
Cookies.txt works now. Thanks.
Also what download speeds should I expect? I am usually at 600KB/s and sometimes it goes up to 1MB/s, but that's it.
I get that they don't have servers setup for this, but I was expecting 2-5MB/s .

**Comment by SH0D4N-1337** [comment]
Cookies.txt works now. Thanks.
Also what download speeds should I expect? I am usually at 600KB/s and sometimes it goes up to 1MB/s, but that's it.
I get that they don't have servers setup for this, but I was expecting 2-5MB/s .
