### ISSUE TITLE
BUG: The newest version can't record the correct data

### ISSUE THREAD

**Issue by MVPAIR** [elvis972602/Kemono-scraper#38]
![image](https://github.com/elvis972602/Kemono-scraper/assets/98071184/330f44e3-b29a-415c-ad46-1bdf9c8ac3a9)
You can try this.
https://kemono.party/fanbox/user/938544

**Comment by 1223334444abc** [comment]
After investigation, I also encountered the same problem here. This should be the same issue as the inability to correctly exclude dates.

**Comment by elvis972602** [comment]
The format of the time seems to have changed, so it can't be parsed correctly.
