### ISSUE TITLE
Error splitting host component:www.kemono.party

### ISSUE THREAD

**Issue by TerryTseng0516** [elvis972602/Kemono-scraper#5]
Sorry for bothering.
When I want to download the post , but it showed error.
kemono-scraper_no_cookies_detection.exe --link https://www.kemono.party/patreon/user/2874302/post/81843545

Error splitting host component:www.kemono.party

I tried to change to other posts but it still have the same problem.

**Comment by elvis972602** [comment]
It seems that the issue might be related to the subdomain in the URL. You can try using the following link without the "www" subdomain:
`https://kemono.party/patreon/user/2874302/post/81843545`
If you still encounter issues, please let me know, and I'll be happy to help you.

**Comment by TerryTseng0516** [comment]
Thanks for helping.

I was tried to delete "https://www" , but still not work. Just deleted "www" is enough to work....

**Comment by elvis972602** [comment]
You are right, because URLs that do not start with `https://` are not legal.
The latest [release](https://github.com/elvis972602/Kemono-scraper/releases/tag/v0.0.8) fixes this problem, and you can use URLs with subdomains normally
