### ISSUE TITLE
has an error

### ISSUE THREAD

**Issue by HuangShun** [elvis972602/Kemono-scraper#8]
link:https://coomer.party/onlyfans/user/loisplz

panic: unmarshal post list error: invalid character '<' looking for beginning of value

goroutine 1 [running]:
github.com/elvis972602/kemono-scraper/kemono.(*Kemono).Start(0xc00015c120)
        C:/Users/elvis/GolandProjects/Kemono-scraper/kemono/kemono.go:233 +0x5d7
main.main()
        C:/Users/elvis/GolandProjects/Kemono-scraper/main/main.go:464 +0x3a65

**Comment by elvis972602** [comment]
This might be a network error during the request process or sending too many requests causing a HTTP 429 error. You can try again, and I'll try to fix this issue quickly.

**Comment by elvis972602** [comment]
It seems like receiving an HTML page response, which starts with '<', so I added error retry logic to FetchPost function. However, I have been unable to reproduce this error even making requests from five different applications. 
So, let me keep it open for now.
